# Generated by npins. Do not edit manually.
# Run `npins update` to refresh pins.
let
  lock = builtins.fromJSON (builtins.readFile ./sources.json);

  fetch = { type, ... }@pin:
    if type == "github" then
      builtins.fetchTarball {
        url = "https://github.com/${pin.owner}/${pin.repo}/archive/${pin.rev}.tar.gz";
        sha256 = pin.sha256;
      }
    else if type == "tarball" then
      builtins.fetchTarball {
        url = pin.url;
        sha256 = pin.sha256;
      }
    else
      abort "npins: unsupported pin type '${type}'";
in
  builtins.mapAttrs (_: fetch) lock
